### PR TITLE
Convert production db backup to modern psql #731

### PR DESCRIPTION
**Pull request by kencho51**
This PR is about:

1. Refractor the script. 
2. Spin up the database container before the main script starts, and stop at the end of the script.
3. Add step to load upgraded database dump into postgreSQL server.
4. Update usage in readme.

### CODE REVIEW

**Review by rija — CHANGES_REQUESTED** [review]
Hi @kencho51


There is no reason to stop the regular database container at the end of the script:
```
echo "Stop database container"
docker stop deployment_database_1
```
 
because this it used for running tests and to support local deployment of gigadb website

**Review by rija — CHANGES_REQUESTED** [review]
@kencho51, in the README, add a note at the top that files-url-updater needs to have been configured as a pre-requisite

**Comment by rija** [comment]
For me. running the conversion command is throwing errors: 

```
> sql/convert_production_db_to_latest_ver.sh
Spin up the database container
Docker Compose is now in the Docker CLI, try `docker compose up`

Starting deployment_database_1 ... done
Go into docker container and store the postgreSQL version
Creating deployment_test_run ... done
Download the production database using file-url-updater
Creating files-url-updater_updater_run ... done

Command is running for date 20210901

Downloading production backup for 20210901
/app/sql/gigadbv3_20210901.backup:                      29.85 MB    2.17 MB/s  
/app/sql/gigadbv3_20210901.backup:                      29.85 MB    2.17 MB/s  
Create production database for the version upgrade
Creating deployment_test_run ... done
CREATE DATABASE
Load the production database into PostgreSQL server
Creating deployment_test_run ... done
pg_restore: connecting to database for restore
pg_restore: creating SCHEMA "public"

...

pg_restore: creating FK CONSTRAINT "public.search_user_id_fkey"
pg_restore: creating ACL "public"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 3397; 0 0 ACL public postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  role "postgres" does not exist
    Command was: REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
...
pg_restore: creating ACL "public.curation_log"
pg_restore: creating ACL "public.dataset_session"
pg_restore: creating ACL "public.file_number"
pg_restore: creating ACL "public.homepage_dataset_type"
pg_restore: creating ACL "public.prefix"
pg_restore: creating ACL "public.sample_number"
WARNING: errors ignored on restore: 1
ERROR: 1
Create folder for database dump if not existed
Dump the production database
```

**Comment by rija** [comment]
Hi @kencho51 

I think  the overall  approach is not quite right.
Manipulating .pgdmp files is quite complex.
The TOC inside the binary backup refers  to indices  that are specific to a database server and are not meant to be transferred.
Additionally restoring PG extensions are not supported and the gigadb binary dump refers to several PG extensions, and there are issues around constraints integrity during  restoring, all that making transferring data that way between servers quite finicky and error-prone. There are ways around it, for example, the code for restoring data in files-url-updater (which must work with that format because that's how CNGB dit it) is quite complex so it can deal with these situations, but that doesn't involve the complexity of version migrations.

I think dumping data as text is the most appropriate approach as it bypasses most of the issues mentioned above and allow most flexibility.

that's the approach described in the docs when using pg_dump: https://www.postgresql.org/docs/9.0/migration.html


But we cannot run the command described there because the database server in files-url-updater was not meant to have exact same configuration as the regular database server nor as the cloud deployed server (let alone a cloud managed service like RDS)

Let me look further to see whether we can adapt the approach from PostgreSQL docs to our situation and/or change the way we configure our databases to get closer to a place we can use the documented approach.

**Comment by rija** [comment]
Hi @kencho51,

A litle bit of progress on this: below I  describe the steps I've used to load CNGB's latest production backup into  9.6 PostgreSQL server locally and on AWS

Pre-requisites: 

* ``./up.sh`` script has been run
* files-url-updater is configured and its pg9_3 container service is running

## Conversion of data

```
cd gigadb/app/tools/files-url-updater

docker-compose run --rm updater ./yii dataset-files/download-restore-backup --latest

docker-compose run --rm updater pg_dump -h pg9_3 -U gigadb  --clean --create --schema=public --no-privileges --no-tablespaces gigadb > sql/db.backup
```

## Upgrading local dev server

```
cd ../../../..

docker-compose stop application

docker-compose run --rm test bash -c "psql -h database -U gigadb -d postgres -c 'drop database gigadb'"

docker-compose run --rm test bash -c "psql -h database -U gigadb -d postgres -c 'create database gigadb'"

docker-compose run --rm test bash -c "psql -h database -U gigadb  < /var/www/gigadb/app/tools/files-url-updater/sql/db.backup"

docker-compose start application
```

## upgrading staging

in GitLab, click ``sd_stop_app`` button in the pipeline

```
ssh -i ~/.ssh/aws-hk-centos7-keys.pem  centos@18.164.141.45 "psql -U gigadb -d postgres -c 'drop database gigadb'"

ssh -i ~/.ssh/aws-hk-centos7-keys.pem  centos@18.164.141.45 "psql -U postgres -d postgres -c 'create database gigadb owner gigadb'"

ssh -i ~/.ssh/aws-hk-centos7-keys.pem  centos@18.164.141.45 'psql -U gigadb' < gigadb/app/tools/files-url-updater/sql/db.backup
```

In GitLab, click ``sd_start_app`` button in pipeline


## upgrading live

in GitLab, click ``ld_stop_app`` button in the pipeline

```
ssh -i ~/.ssh/aws-hk-centos7-keys.pem  centos@18.164.112.113 "psql -U gigadb -d postgres -c 'drop database gigadb'"

ssh -i ~/.ssh/aws-hk-centos7-keys.pem  centos@18.164.112.113 "psql -U postgres -d postgres -c 'create database gigadb owner gigadb'"

ssh -i ~/.ssh/aws-hk-centos7-keys.pem  centos@18.164.112.113 'psql -U gigadb' < gigadb/app/tools/files-url-updater/sql/db.backup
```

In GitLab, click ``ld_start_app`` button in pipeline

## change to the script

Based on the above, the conversion script``sql/convert_production_db_to_latest_ver.sh`` can be changed to:

```
#!/usr/bin/env bash

cd gigadb/app/tools/files-url-updater

#download and load production data into local legacy PostgreSQL server
docker-compose run --rm updater ./yii dataset-files/download-restore-backup --latest

#export production data as text (ensuring only the strictly necessary data is exported)
docker-compose run --rm updater pg_dump -h pg9_3 -U gigadb  --clean --create --schema=public --no-privileges --no-tablespaces gigadb > sql/db.backup

cd ../../../..

```

And its probably better for it to be in ``ops/scripts/`` where we have our other operational bash scripts, ``sql/`` is meant for SQL scripts only.
Also we need ``gigadb/app/tools/files-url-updater/sql/db.backup`` to be in .gitignore.


After the changes are made, we should be able to merge this PR. 
That doesn't mean the functionality is completely functional though. 

The legacy production backup ignore our Yii database migrations, so we need to find a way to integrate them, but it should be a separate PR, associated with a new user story and task for the new sprint

**Comment by kencho51** [comment]
Hi @rija , 

The database dump by the updater will be in version `9.3.25`,  would it be a concern as it should be `9.6+` mentioned in [this ticket](https://github.com/gigascience/gigadb-website/issues/731)?
The below is an example output of the dump:
```
.........
pg_dump: saving encoding = UTF8
pg_dump: saving standard_conforming_strings = on
pg_dump: saving search_path = 
--
-- PostgreSQL database dump
--

-- Dumped from database version 9.3.25
-- Dumped by pg_dump version 9.3.25
-- Started on 2021-09-03 04:44:25 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
............
```

**Comment by rija** [comment]
@kencho51, no it isn't a concern. The text export from pg_dump can be imported by and version. 
the problem we had is that binary format are version specific. Text format aren't

**Review by rija — APPROVED** [review]
I confirm, it works fine now

**Pull request merged**
